//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLATAFORMA_VIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.COMENTARIO = new HashSet<COMENTARIO>();
            this.MATERIAL = new HashSet<MATERIAL>();
            this.PREGUNTA = new HashSet<PREGUNTA>();
            this.RESPUESTA = new HashSet<RESPUESTA>();
        }
    
        public int Id { get; set; }
        public string Nombre_Curso { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Usuario { get; set; }
    
        public virtual ICollection<COMENTARIO> COMENTARIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<MATERIAL> MATERIAL { get; set; }
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
        public virtual ICollection<RESPUESTA> RESPUESTA { get; set; }
    }
}
