//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLATAFORMA_VIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosValidar
    {
        public int Id { get; set; }
        public string Nick { get; set; }
        public string Pass { get; set; }
    }
}
