//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLATAFORMA_VIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public int Id { get; set; }
        public string Material1 { get; set; }
        public string Tipo_Material { get; set; }
        public string Titulo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_usuario { get; set; }
        public int Id_Curso { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
