//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLATAFORMA_VIRTUAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AULA_VIRTUALEntities : DbContext
    {
        public AULA_VIRTUALEntities()
            : base("name=AULA_VIRTUALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMENTARIO> COMENTARIO { get; set; }
        public DbSet<CURSO> CURSO { get; set; }
        public DbSet<MATERIAL> MATERIAL { get; set; }
        public DbSet<PREGUNTA> PREGUNTA { get; set; }
        public DbSet<RESPUESTA> RESPUESTA { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<DatosValidar> DatosValidar { get; set; }
    }
}
