//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLATAFORMA_VIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.COMENTARIO = new HashSet<COMENTARIO>();
            this.CURSO = new HashSet<CURSO>();
            this.MATERIAL = new HashSet<MATERIAL>();
            this.PREGUNTA = new HashSet<PREGUNTA>();
            this.RESPUESTA = new HashSet<RESPUESTA>();
        }
    
        public int Id { get; set; }
        public string Nick { get; set; }
        public string Pass { get; set; }
        public byte[] Img_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string sexo { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Telefono { get; set; }
        public string Carrera { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Lenguaje_Defecto { get; set; }
        public string e_mail { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ICollection<COMENTARIO> COMENTARIO { get; set; }
        public virtual ICollection<CURSO> CURSO { get; set; }
        public virtual ICollection<MATERIAL> MATERIAL { get; set; }
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
        public virtual ICollection<RESPUESTA> RESPUESTA { get; set; }
    }
}
